### ISSUE TITLE
KeyAnchor, KeyRegistration or KeysetRoot -- role of each

### ISSUE THREAD

**Issue by GildedHonour** [Holo-Host/DeepKey#2]
I'm working on a similar app. I've read the documetation of this app, it's still not clear. Which of these 3 is on the top of the hierarchy in your app: KeyAnchor, KeyRegistration or KeysetRoot? What's the role of each of these? And what's the work flow in general in regards to these?

**Comment by zo-el** [comment]
@GildedHonour 

KeysetRoot-->keyRegistration-->KeyAnchor
**KeysetRoot:**  This is the public entry that is sort of the root entry that is commented during Genesis and that lets the conductor know that the app is initialized

**KeyRegistration:** This entry as the name suggests is committed when a key has to register.

**KeyAnchor:** This entry is committed when the Key is registered as well it's a neat way to figure out if a key is registered/updated/deleted.
